// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxW7qMf-_926cQlefwl--hFuOKU199hag',
    appId: '1:890198304699:web:cc56135c7508586902869e',
    messagingSenderId: '890198304699',
    projectId: 'flutterfirebase-609a2',
    authDomain: 'flutterfirebase-609a2.firebaseapp.com',
    storageBucket: 'flutterfirebase-609a2.appspot.com',
    measurementId: 'G-Z4PWCB1S1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8H7aJ1_rATjuEQzZeRMrGHwswGQ1DamA',
    appId: '1:890198304699:android:de183482ae3d907c02869e',
    messagingSenderId: '890198304699',
    projectId: 'flutterfirebase-609a2',
    storageBucket: 'flutterfirebase-609a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBWApHVgrK7P9J9BY5ofqH3TtAWIdkow',
    appId: '1:890198304699:ios:bfe5185e24d1fac502869e',
    messagingSenderId: '890198304699',
    projectId: 'flutterfirebase-609a2',
    storageBucket: 'flutterfirebase-609a2.appspot.com',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSBWApHVgrK7P9J9BY5ofqH3TtAWIdkow',
    appId: '1:890198304699:ios:bfe5185e24d1fac502869e',
    messagingSenderId: '890198304699',
    projectId: 'flutterfirebase-609a2',
    storageBucket: 'flutterfirebase-609a2.appspot.com',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxW7qMf-_926cQlefwl--hFuOKU199hag',
    appId: '1:890198304699:web:5cba34a89380330f02869e',
    messagingSenderId: '890198304699',
    projectId: 'flutterfirebase-609a2',
    authDomain: 'flutterfirebase-609a2.firebaseapp.com',
    storageBucket: 'flutterfirebase-609a2.appspot.com',
    measurementId: 'G-7BG2V1YGB0',
  );
}
